service: golang-rnd

provider:
  name: google
  runtime: go111
  project: adept-mountain-238503
  credentials: /Volumes/Storage/development/creds/adept-mountain-238503-24a5a1e5e418.json
  stage: ${opt:stage,'dev'}

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - test/**
    - readme.md
    - .env*
    - Makefile

# Custom Variables
custom:
  stages:
    - local
    - dev
    - staging
    - prod
  dbUrl:
    local: mongodb://localhost:27017/mnapi
    dev: mongodb://172.31.3.201:27017/growthfunnel-dev
    staging: mongodb://172.31.14.121:27017/crazyengage-dev
    prod: mongodb://mongodb:password@172.31.13.179:35071/crazyengage?authSource=admin
  dbName:
    local: mnapi
    dev: growthfunnel-dev
    staging: crazyengage-dev
    prod: crazyengage

  # Environment Variables
  environment:
    ENV: ${self:provider.stage}
    MONGODB_URL: ${self:custom.dbUrl.${self:provider.stage}}
    DB_NAME: ${self:custom.dbName.${self:provider.stage}}

functions:
  sender:
    handler: SendNotification
    timeout: 2s
    memorySize: 1024
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: projects/${self:provider.project}/topics/notification

plugins:
  - serverless-offline
  - serverless-stage-manager
  - serverless-google-cloudfunctions
